# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: e4625c1
_src_path: gh:/EasyScience/EasyProjectTemplate
description: Python package for bragg-edge analysis
max_python: '3.12'
min_python: '3.9'
orgname: EasyScience
packagename: easyimaging
prettyname: Easyimaging
projectname: EasyImaging
year: 2024
